### ISSUE TITLE
g++: error: gfortran: No such file or directory

### ISSUE THREAD

**Issue by wenyulai** [ktchu/LSMLIB#13]
when i configure --with-samrai, after make and make install, and the cd examples/parallel/2d,
then input make here, there error happens  g++: error: gfortran: No such file or directory. ???

**Comment by ktchu** [comment]
Apologies for the long delay in responding (this project has been in hibernation until very recently).

It looks like you do not have a fortran compiler installed on your system. After installing a fortran compiler, you should no longer encounter this error.
