### ISSUE TITLE
configure error , need to use parallel

### ISSUE THREAD

**Issue by ermore** [ktchu/LSMLIB#14]
I want to use lsmlib lib, I clone the complete code and switch to dev-samrai branch. 
I created a folder call "build" and entered it,execute the following command:
```
../configure --with-samrai=/home/ermore/opt/SAMRAI-3.11.2 --with-intelmpi=/home/ermore/intel/compilers_and_libraries_2019.3.199/linux/mpi
```
I get something error as follow:
```
...
config.status: creating src/toolbox/fast_marching_method/Makefile
config.status: creating src/toolbox/fast_marching_method/Makefile.depend
config.status: creating src/toolbox/field_extension/Makefile
config.status: creating src/toolbox/geometry/Makefile
config.status: error: cannot find input file: `src/toolbox/geometry/lsm_curvature2d.f.in'
```
Looks like a configuration problem, or an lsmlib file directory problem?

**Comment by ktchu** [comment]
Apologies for the long delay in responding (this project has been in hibernation until very recently).

Thank you for notifying us of the bug in the build system. The build system is currently being migrated to CMake (from autotools).

Unfortunately, if you need the parallel version of LSMLIB, it is currently broken (a dependency required for support of parallel computations has changed). We are in the process of factoring the parallel LSMLIB capabilities to a separate project but will not be updating it. It will be left publicly available for anybody who would like to refer to it or upgrade it for their own purposes.
