### ISSUE TITLE
mex: compile of ' "computeExtensionFields2d.c"' failed.

### ISSUE THREAD

**Issue by petteriTeikari** [ktchu/LSMLIB#3]
Hi, 

I tried to compile your LSMLIB but hit that in 64-bit Ubuntu 14.04:

<code>../../../include/lsm_fast_marching_method.h:124: note: expected ‘int *’ but argument is of type ‘double *’
computeExtensionFields2d.c:192: error: too few arguments to function ‘computeExtensionFields2d’

```
mex: compile of ' "computeExtensionFields2d.c"' failed.
```

make[3]: **\* [computeExtensionFields2d.mexa64] Error 1
</code>

with sudo make after having the following configure:

<code>sudo ./configure --with-matlab=/usr/local/MATLAB/R2013a/ --with-matlab-install-dir=~/Dropbox/LSMLIB/
</code>

Any idea of what is going on there?

**Comment by ktchu** [comment]
Hi Petteri,

Thank you for your interest in LSMLIB.  It looks like you have found a bug in the MATLAB wrapper for LSMLIB.  That functionality has not been used for a while, so the fast marching method wrapper is probably out of date.

If you do not need MATLAB, I would recommend configuring using the '--without-MATLAB' option.  If you need MATLAB, you'll probably have to make changes to computeExtensionFields2d.c to set the 'extension_mask' variable.

Sorry for the inconvenience.  We no longer have funding to actively support LSMLIB but can try to help with minor updates.

BTW, what are you interested in using level set methods for?

Hope you're having a great day!

Cheers,
Kevin
_______________________________ 

Breathe. Smile. The Future is Bright!
_______________________________
